version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile.prod
            args:
                NODE_IMAGE_TAG: $NODE_IMAGE_TAG
        depends_on: 
            - db
        container_name: blog272
        environment:
            - MONGO_HOSTNAME=db
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
            - PORT=5000
            - JWT_SECRET=$JWT_SECRET
        ports:
            - "5000:5000"
        restart: always
    db:
        image: "mongo:4.4.5-bionic"
        container_name: mongo-db
        ports: 
            - "27017:27017"
        restart: always
    web-test-features:
        build:
            context: .
            dockerfile: docker/Dockerfile.acc
            args:
                NODE_IMAGE_TAG: $NODE_IMAGE_TAG
        depends_on:
            - web
        environment:
            - BLOG272_HOST=web
            - BLOG272_PORT=5000
